// <auto-generated />
using System;
using CatalogsBooksAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogsBooksAPI.Migrations
{
    [DbContext(typeof(CatalogsBooksContext))]
    [Migration("20260303132235_fixed required series id in books table ")]
    partial class fixedrequiredseriesidinbookstable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogsBooksAPI.Models.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<int?>("AuthorID")
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CanDownload")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CoverAlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownloadLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PagesCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PublicationDate")
                        .HasColumnType("date");

                    b.Property<int?>("SeireID")
                        .HasColumnType("int");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("SeireID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.BookList", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("ListID")
                        .HasColumnType("int");

                    b.HasKey("BookID", "ListID");

                    b.HasIndex("ListID");

                    b.ToTable("BookLists");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.BookSeire", b =>
                {
                    b.Property<int>("SeireID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeireID"));

                    b.Property<string>("SeireName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeireID");

                    b.ToTable("BookSeires");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<double>("RateValue")
                        .HasColumnType("float");

                    b.Property<string>("ReviewText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.HasIndex("AccountID");

                    b.HasIndex("BookID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserList", b =>
                {
                    b.Property<int>("ListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("ListName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListID");

                    b.HasIndex("AccountID");

                    b.ToTable("UserLists");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserPreferedAuthor", b =>
                {
                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BookID")
                        .HasColumnType("int");

                    b.HasKey("AccountID", "AuthorName");

                    b.HasIndex("AuthorName")
                        .IsUnique();

                    b.HasIndex("BookID");

                    b.ToTable("UserPreferedAuthors");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserPreferredCategory", b =>
                {
                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubCategory")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("BookID")
                        .HasColumnType("int");

                    b.HasKey("AccountID", "Category", "SubCategory");

                    b.HasIndex("BookID");

                    b.HasIndex("Category", "SubCategory");

                    b.ToTable("UserPreferedCategories");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.ViewedBook", b =>
                {
                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.HasKey("AccountID", "BookID");

                    b.HasIndex("BookID");

                    b.ToTable("ViewedBooks");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Book", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID");

                    b.HasOne("CatalogsBooksAPI.Models.BookSeire", "BookSeire")
                        .WithMany("Books")
                        .HasForeignKey("SeireID");

                    b.Navigation("Account");

                    b.Navigation("BookSeire");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.BookList", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Book", "Book")
                        .WithMany("ListItems")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.UserList", "UserList")
                        .WithMany("BookLists")
                        .HasForeignKey("ListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Review", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithMany("Reviews")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserList", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithMany("UserLists")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserPreferedAuthor", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithMany("UserPreferedAuthors")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("AuthorName")
                        .HasPrincipalKey("AuthorName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Book", "Book")
                        .WithMany("UserPreferedAuthors")
                        .HasForeignKey("BookID");

                    b.Navigation("Account");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserPreferredCategory", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithMany("UserPreferedCategories")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Book", "Book")
                        .WithMany("UserPreferedCategories")
                        .HasForeignKey("BookID");

                    b.HasOne("CatalogsBooksAPI.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("Category", "SubCategory")
                        .HasPrincipalKey("Category", "SubCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.ViewedBook", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithMany("ViewedBooks")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Book", "Book")
                        .WithMany("ViewedBooks")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Account", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Reviews");

                    b.Navigation("UserLists");

                    b.Navigation("UserPreferedAuthors");

                    b.Navigation("UserPreferedCategories");

                    b.Navigation("ViewedBooks");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Book", b =>
                {
                    b.Navigation("ListItems");

                    b.Navigation("Reviews");

                    b.Navigation("UserPreferedAuthors");

                    b.Navigation("UserPreferedCategories");

                    b.Navigation("ViewedBooks");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.BookSeire", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserList", b =>
                {
                    b.Navigation("BookLists");
                });
#pragma warning restore 612, 618
        }
    }
}
