// <auto-generated />
using System;
using CatalogsBooksAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogsBooksAPI.Migrations
{
    [DbContext(typeof(CatalogsBooksContext))]
    [Migration("20260502151950_Added map for delete author and category  as it never exist")]
    partial class Addedmapfordeleteauthorandcategoryasitneverexist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogsBooksAPI.Models.Account", b =>
                {
                    b.Property<int>("AccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountID"));

                    b.Property<string>("AccountState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorID"));

                    b.Property<int?>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorID");

                    b.HasIndex("AccountID")
                        .IsUnique()
                        .HasFilter("[AccountID] IS NOT NULL");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<bool>("CanDownload")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("CoverAlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownloadLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PagesCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PublicationDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.BookList", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("ListID")
                        .HasColumnType("int");

                    b.HasKey("BookID", "ListID");

                    b.HasIndex("ListID");

                    b.ToTable("BookLists");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("MainCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sbucategory")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<double>("RateValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.HasIndex("AccountID");

                    b.HasIndex("BookID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Series", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<string>("SeriesName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookID");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserList", b =>
                {
                    b.Property<int>("ListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("ListName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListID");

                    b.HasIndex("AccountID");

                    b.ToTable("UserLists");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserPreferedAuthor", b =>
                {
                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<int?>("BookID")
                        .HasColumnType("int");

                    b.HasKey("AuthorID", "AccountID");

                    b.HasIndex("AccountID");

                    b.HasIndex("BookID");

                    b.ToTable("UserPreferedAuthors");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserPreferredCategory", b =>
                {
                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("BookID")
                        .HasColumnType("int");

                    b.HasKey("AccountID", "CategoryID");

                    b.HasIndex("BookID");

                    b.HasIndex("CategoryID");

                    b.ToTable("UserPreferedCategories");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.ViewedBook", b =>
                {
                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<int?>("BookID1")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountID", "BookID");

                    b.HasIndex("BookID");

                    b.HasIndex("BookID1");

                    b.ToTable("ViewedBooks");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Author", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithOne("Author")
                        .HasForeignKey("CatalogsBooksAPI.Models.Author", "AccountID");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Book", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.BookList", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Book", "Book")
                        .WithMany("ListItems")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.UserList", "UserList")
                        .WithMany("BookLists")
                        .HasForeignKey("ListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("UserList");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Review", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithMany("Reviews")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Book", "Book")
                        .WithMany("Reviews")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Series", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Book", "Books")
                        .WithOne("Series")
                        .HasForeignKey("CatalogsBooksAPI.Models.Series", "BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Books");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserList", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithMany("UserLists")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserPreferedAuthor", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithMany("UserPreferedAuthors")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Author", "Author")
                        .WithMany("UserPreferedAuthor")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Book", null)
                        .WithMany("UserPreferedAuthors")
                        .HasForeignKey("BookID");

                    b.Navigation("Account");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserPreferredCategory", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithMany("UserPreferedCategories")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Book", null)
                        .WithMany("UserPreferedCategories")
                        .HasForeignKey("BookID");

                    b.HasOne("CatalogsBooksAPI.Models.Category", "Category")
                        .WithMany("UserPreferredCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.ViewedBook", b =>
                {
                    b.HasOne("CatalogsBooksAPI.Models.Account", "Account")
                        .WithMany("ViewedBooks")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Book", null)
                        .WithMany("ViewedBooks")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogsBooksAPI.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookID1");

                    b.Navigation("Account");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Account", b =>
                {
                    b.Navigation("Author");

                    b.Navigation("Reviews");

                    b.Navigation("UserLists");

                    b.Navigation("UserPreferedAuthors");

                    b.Navigation("UserPreferedCategories");

                    b.Navigation("ViewedBooks");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Author", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("UserPreferedAuthor");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Book", b =>
                {
                    b.Navigation("ListItems");

                    b.Navigation("Reviews");

                    b.Navigation("Series");

                    b.Navigation("UserPreferedAuthors");

                    b.Navigation("UserPreferedCategories");

                    b.Navigation("ViewedBooks");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.Category", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("UserPreferredCategories");
                });

            modelBuilder.Entity("CatalogsBooksAPI.Models.UserList", b =>
                {
                    b.Navigation("BookLists");
                });
#pragma warning restore 612, 618
        }
    }
}
